# Generated by Django 4.2.18 on 2025-08-17 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concertcapsuleapi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="concert",
            old_name="artist_id",
            new_name="artist",
        ),
        migrations.RenameField(
            model_name="concert",
            old_name="venue_id",
            new_name="venue",
        ),
        migrations.RenameField(
            model_name="userconcert",
            old_name="concert_id",
            new_name="concert",
        ),
        migrations.RenameField(
            model_name="userconcert",
            old_name="user_id",
            new_name="user",
        ),
    ]
