# Generated by Django 5.2.5 on 2025-08-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concertcapsuleapi", "0002_rename_artist_id_concert_artist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="setlist_fm_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="venue",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="venue",
            name="state",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
