# Generated by Django 5.2.5 on 2025-08-21 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concertcapsuleapi", "0003_venue_setlist_fm_id_alter_venue_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist",
            name="genres",
        ),
    ]
