# Generated by Django 5.2.5 on 2025-08-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concertcapsuleapi", "0004_remove_artist_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concert",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
