# Generated by Django 5.2.5 on 2025-08-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concertcapsuleapi", "0005_alter_concert_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concert",
            name="tour_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
