# Generated by Django 5.2.5 on 2025-08-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concertcapsuleapi", "0006_alter_concert_tour_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
