# Generated by Django 5.2.5 on 2025-08-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concertcapsuleapi", "0007_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
