# Generated by Django 5.2.5 on 2025-08-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concertcapsuleapi", "0008_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uid_firebase",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
