# Generated by Django 5.2.5 on 2025-08-26 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concertcapsuleapi", "0009_alter_user_uid_firebase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userconcert",
            name="concert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userconcerts",
                to="concertcapsuleapi.concert",
            ),
        ),
    ]
