# Generated by Django 5.2.5 on 2025-08-31 19:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concertcapsuleapi", "0011_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="userconcert",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
