# Generated by Django 5.2.5 on 2025-09-03 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concertcapsuleapi", "0012_userconcert_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="concertcapsuleapi.user",
                    ),
                ),
                (
                    "user_concert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="concertcapsuleapi.userconcert",
                    ),
                ),
            ],
        ),
    ]
