# Generated by Django 5.2.5 on 2025-09-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concertcapsuleapi", "0013_like"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user", "user_concert")},
        ),
    ]
