# Generated by Django 5.2.5 on 2025-09-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concertcapsuleapi", "0014_alter_like_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="userconcert",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
    ]
