# Generated by Django 5.2.5 on 2025-09-12 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concertcapsuleapi", "0015_userconcert_pinned"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userconcert",
            unique_together={("concert", "user")},
        ),
    ]
