"""
  user.py
  
  Defines the Django model for a user, including:
  uid generated by Firebase, first name, last name, and username (provided by the user)
"""

from django.db import models


class User(models.Model):
    """Represents a user in the database"""
    uid_firebase = models.CharField(max_length=50, unique=True)
    first_name = models.CharField(max_length=50, blank=True, null=True)
    last_name = models.CharField(max_length=50, blank=True, null=True)
    username = models.CharField(max_length=50, unique=True)
